features:
  numerical:
    - age
    - salary
  categorical:
    - city
steps:
    categorical:
       imputer: SimpleImputer
       encoder: OneHotEncoder
    numerical:
       imputer: SimpleImputer
       scaler: StandardScaler

